Simplify initialization of LoggingHandler.logger.
googleapis/java-logging pull request #703
Opened 2021-09-30 18:48 UTC by benjaminp

getLogging() was called in the constructor of LoggingHandler. So, there's no reason to have lazy initialization for the logger.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-logging/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

2021-10-13 17:32 UTC, benjaminp commented on google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java
> +    expectLastCall().times(2, 2);
It gets called twice because `handler.close` is called twice starting on line 571.

2021-10-19 11:06 UTC, minherz commented on google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingHandlerTest.java
> +    expectLastCall().times(2, 2);
nit: given PR refactors the code, should we remove one of the calls?

2021-10-19 11:07 UTC, minherz approved these changes

2021-10-25 10:14 UTC, minherz requested changes
we should make sure that after `close()` is called it is no longer possible to use the same `logging` instance

2021-11-07 15:44 UTC, minherz approved these changes

2022-01-01 17:29 UTC, minherz commented
The change of this PR is implemented in #812

2022-01-01 17:29 UTC, closed without merging